[package]
name = "alphazero_nn"
version = "0.1.0"
edition = "2024"

[dependencies]
candle-core = { git = "https://github.com/huggingface/candle.git"}
candle-nn = { git = "https://github.com/huggingface/candle.git"}

[features]
default = ["cuda"]
cuda = ["candle-core/cuda", "candle-nn/cuda"]
