[package]
name = "alphazero_nn"
version = "0.1.0"
edition = "2024"

[dependencies]
candle-core = { workspace = true }
candle-nn = { workspace = true }

[features]
default = []
cuda = ["candle-core/cuda", "candle-nn/cuda"]
cudnn = ["candle-core/cudnn", "candle-nn/cudnn"]
